
// Objective-C API for talking to the following Go packages
//
//	gitlab.com/connect.club/app-common.git
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Common_FRAMEWORK_H__
#define __Common_FRAMEWORK_H__

#include "Common.objc.h"
#include "Universe.objc.h"

#endif
